### ISSUE TITLE
Predicting cluster membership in new samples

### ISSUE THREAD

**Issue by TSI-PTG** [UBod/apcluster#8]
Dear Dr Bodenhofer and apcluster team, 

I am hoping to get your insight and direction on approaches to predicting cluster membership in new samples after establishing cluster with affinity propagation. 

Thanks, 

Patrick

**Comment by UBod** [comment]
Thanks for the interesting question, @TSI-PTG! This is an issue several people have thought about before. I have been receiving several requests for integrating a `predict()` method into the `apcluster` package. The reason why I have not included it yet is that, in order to have a function that is fully compatible with other implementations of the `predict()` method, I would have had to include much more information in an `APResult` object, which would have required major redesign efforts. If I may, let me refer to a reply I once gave on stackoverflow: [https://stackoverflow.com/questions/34932692/using-the-apcluster-package-in-r-it-is-possible-to-score-unclustered-data-poi](https://stackoverflow.com/questions/34932692/using-the-apcluster-package-in-r-it-is-possible-to-score-unclustered-data-poi); my post contains the implementation of crude helper function `predict.apcluster()` that probably does what you need. I hope that helps.
